-
  branches:
    only:
      - master

  image: Visual Studio 2022
  version: 6.0.0-master-build.{build}
  configuration: Release

  skip_commits:
    files:
      - docs/*

  #---------------------------------#
  #  Install .NET                   #
  #---------------------------------#
  install:
    - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
    - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
    - ps: Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1"
    - ps: '& "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Channel 3.1 -InstallDir $env:DOTNET_INSTALL_DIR'
    - ps: '& "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Channel 5.0 -InstallDir $env:DOTNET_INSTALL_DIR'
    - ps: '& "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Channel 6.0 -InstallDir $env:DOTNET_INSTALL_DIR'
    - ps: '& "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Channel 7.0 -InstallDir $env:DOTNET_INSTALL_DIR'
    - ps: '& "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Channel 8.0 -InstallDir $env:DOTNET_INSTALL_DIR'
    - ps: '& "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Channel 9.0 -InstallDir $env:DOTNET_INSTALL_DIR'
    - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
    - ps: dotnet --info

  before_build:
    - dotnet restore
    - msbuild /restore

  build:
    verbosity: minimal

  artifacts:
    - path: 'artifacts\package\release\*.nupkg'

  deploy:
    provider: NuGet
    api_key:
      secure: orcP0C1iuBVKxnv/uAUehgU1KEI/lCpbSxDqbckd3sZ7XxcuENj6PrExs6SdJIf1
    skip_symbols: false
    artifact: /.*\.nupkg/

-
  branches:
    only:
      - development

  image: Visual Studio 2022
  version: 6.0.0-dev-build.{build}
  configuration: Release

  skip_commits:
    files:
      - docs/*

  #---------------------------------#
  #  Install .NET                   #
  #---------------------------------#
  install:
    - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
    - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
    - ps: Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1"
    - ps: '& "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Channel 3.1 -InstallDir $env:DOTNET_INSTALL_DIR'
    - ps: '& "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Channel 5.0 -InstallDir $env:DOTNET_INSTALL_DIR'
    - ps: '& "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Channel 6.0 -InstallDir $env:DOTNET_INSTALL_DIR'
    - ps: '& "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Channel 7.0 -InstallDir $env:DOTNET_INSTALL_DIR'
    - ps: '& "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Channel 8.0 -InstallDir $env:DOTNET_INSTALL_DIR'
    - ps: '& "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Channel 9.0 -InstallDir $env:DOTNET_INSTALL_DIR'
    - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
    - ps: dotnet --info

  before_build:
    - dotnet restore
    - msbuild /restore

  build:
    verbosity: minimal

  artifacts:
    - path: 'artifacts\package\release\*.nupkg'
